### ISSUE TITLE
kitchen and bistro inside - versions of scenes from demo videos

### ISSUE THREAD

**Issue by tigrazone** [TU-Clausthal-Rendering/ReSTIR-FG#2]
can your version of scenes is downloadable?
it is impressive

**Comment by SirKero** [comment]
The kitchen scene from the demo contains some models whose licenses do not allow sharing. However, we plan to make a shareable version of the Kitchen scene available soon.

The inside of the Bistro is available at: https://developer.nvidia.com/orca/amazon-lumberyard-bistro . 
Our version has some modified materials and some lights were turned off. I can probably add a .pyscene for the Bistro with the next update.

**Comment by tigrazone** [comment]
I know original scenes. And share of your variants is good idea. Your modifications from videopresentation is awesome

**Comment by SirKero** [comment]
The Bistro and Kitchen scenes are now available.
(https://github.com/TU-Clausthal-Rendering/ReSTIR-FG/releases/tag/1.03)
